pring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: status-checker
          uri: lb://status-checker
          predicates:
            - Path=/statusChecker/**

        - id: status-simulator
          uri: lb://status-simulator
          predicates:
            - Path=/statusSimulator/**

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true