spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        lower-case-service-id: true
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
      routes:
        - id: status-checker
          uri: lb://STATUS-CHECKER/statusChecker
          predicates:
            - Path=/statusChecker/**

        - id: status-simulator
          uri: lb://STATUS-SIMULATOR/statusSimulator
          predicates:
            - Path=/statusSimulator/**


server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
  instance:
    preferIpAddress: true