spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: status-checker
          uri: http://localhost:8080
          predicates:
            - Path=/statusChecker/checkStatusOfVehicles

        - id: status-simulator
          uri: http://localhost:8081
          predicates:
            - Path=/statusSimulator/getVehicleStatuses


server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true