# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps: 
      - checkout
      - run: cd build/docker_build/scripts/ && ./deploy.sh
      - store_artifacts:
            path: ~/repo/features/screenshots
