spring:
  application:
    name: eureka-discovery
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
logging:
  level:
    com.netflix.discovery: 'OFF'
    com.netflix.eureka: 'OFF'
